#!/usr/bin/env bash
#
# Netlink Aegis - one-command deployment bootstrap.
#
# Clone the repo on any server and run this script to build the Netlink-branded
# images and bring the stack up. Defaults to PLAIN HTTP on the host's IP (no
# certificates), which is the quickest way to get running on a trusted network.
# Pass --https for self-signed HTTPS, or use DEPLOY.md for a real-cert
# production deployment.
#
# Usage:
#   ./deploy.sh                       # HTTP, auto-detect this host's IP
#   ./deploy.sh 192.168.1.50          # HTTP on a specific IP/hostname
#   ./deploy.sh grc.example.com --https   # self-signed HTTPS
#   NODE_BUILD_HEAP_MB=4096 ./deploy.sh   # cap frontend build memory on tiny hosts
#
set -euo pipefail

MODE="http"
FQDN=""

for arg in "$@"; do
  case "$arg" in
    --https) MODE="https" ;;
    --http)  MODE="http" ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) FQDN="$arg" ;;
  esac
done

cd "$(dirname "$0")"

# --- Prerequisites ----------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker is not installed. Install Docker first: https://docs.docker.com/engine/install/" >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' (v2) is not available. Install the Docker Compose plugin." >&2
  exit 1
fi

# --- Resolve the host address (CISO_FQDN) -----------------------------------
if [ -z "$FQDN" ]; then
  FQDN="${CISO_FQDN:-}"
fi
if [ -z "$FQDN" ]; then
  # Best-effort auto-detection of the primary outbound IP.
  FQDN="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
fi
if [ -z "$FQDN" ]; then
  read -r -p "Enter this host's IP address or hostname (no scheme, no port): " FQDN
fi
if [ -z "$FQDN" ]; then
  echo "ERROR: no host address provided. Re-run as: ./deploy.sh <ip-or-hostname>" >&2
  exit 1
fi

# --- Tune frontend build memory for small hosts -----------------------------
HEAP="${NODE_BUILD_HEAP_MB:-}"
if [ -z "$HEAP" ] && [ -r /proc/meminfo ]; then
  TOTAL_MB="$(awk '/MemTotal/{print int($2/1024)}' /proc/meminfo)"
  if   [ "$TOTAL_MB" -lt 5000 ]; then HEAP=4096
  elif [ "$TOTAL_MB" -lt 9216 ]; then HEAP=6144
  else HEAP=8192
  fi
  if [ "$TOTAL_MB" -lt 4096 ]; then
    echo "WARNING: only ${TOTAL_MB} MB RAM detected. The frontend build may run out of"
    echo "         memory. Consider adding swap before continuing (see DEPLOY.md)."
  fi
fi
HEAP="${HEAP:-8192}"

# --- Write the env file -----------------------------------------------------
ENV_FILE=".env.${MODE}"
COMPOSE_FILE="docker-compose-${MODE}.yml"

{
  echo "# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "CISO_FQDN=${FQDN}"
  echo "NODE_BUILD_HEAP_MB=${HEAP}"
} > "$ENV_FILE"

SCHEME="http"; [ "$MODE" = "https" ] && SCHEME="https"

echo "---------------------------------------------------------------"
echo " Netlink Aegis deployment"
echo "   mode:        ${MODE} (${SCHEME})"
echo "   host:        ${FQDN}"
echo "   build heap:  ${HEAP} MB"
echo "   env file:    ${ENV_FILE}"
echo "   compose:     ${COMPOSE_FILE}"
echo "---------------------------------------------------------------"
if [ "$MODE" = "http" ]; then
  echo "NOTE: HTTP traffic is UNENCRYPTED. Use only on a trusted network."
fi
echo "Building images and starting the stack (first run can take several minutes)..."

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build

echo
echo "Stack is up. Open: ${SCHEME}://${FQDN}/"
if [ "$MODE" = "https" ]; then
  echo "(Self-signed cert: accept the one-time browser 'not private -> proceed' warning.)"
fi
echo
echo "Create your first admin account:"
echo "  docker compose --env-file ${ENV_FILE} -f ${COMPOSE_FILE} exec backend poetry run python manage.py createsuperuser"
